### ISSUE TITLE
Android Browser - 4.3 - First tap on a bellows does not release the active state

### ISSUE THREAD

**Issue by mobify-derrick** [mobify/bellows#30]
Device: Samsung Galaxy Note 3
OS: Android 4.3
Browser: Default Android

Steps:
1. Browse to any example
2. Tap on a bellows header
<Note the active state remains after the tap>
3. Tap on the same bellows or another

Results:
The bellows header does not release the active state

Expected:
The active state should be released on properly

**Comment by tedtate** [comment]
@mobify-derrick is this still a valid issue?

**Comment by mobify-derrick** [comment]
@tedtate actually this was addressed, closing
