### ISSUE TITLE
Provide a version of Bellows with all dependencies built in

### ISSUE THREAD

**Issue by chug2k** [mobify/bellows#49]
When directly downloading and using `bellows.js` from `dist` of this repo, I got an error on line 45:
  ```
  Plugin.create('bellows', Bellows, {
```

This was especially confusing because `Plugin` does exist for me when I type it into the browser console, I think it may be part of Chrome or something. Anyway, I had to to get the latest `plugin.js` from mobify/plugin and also include it via `<script src...>` on my page.

**Comment by tedtate** [comment]
I don't think we have any plans to add this in the immediate future. If anyone is interested in creating a PR for this I would be happy to merge it in though :smile:
