### ISSUE TITLE
Add to npm, enable UMD

### ISSUE THREAD

**Issue by danieldunderfelt** [mobify/bellows#57]
Hi!

It would be great to have this library on NPM and to be able to use it through CommonJS or ES6 modules easily.

I haven't found many good accordion libraries out there, and no other that use Velocity. Nailing the distribution for Bellows would enable you to really gain users.

Thanks!

**Comment by donnielrt** [comment]
Hey @danieldunderfelt, thanks for the suggestion and apologies for the delayed response! 

We don't have the bandwidth to work on npm compatibility since that's not a supported use-case at present. If you could open a PR for the feature, we'd be happy to review and get it merged in, however :)
