### ISSUE TITLE
Sticky header

### ISSUE THREAD

**Issue by nuthinking** [mobify/bellows#58]
On mobile, it would be very useful to have the header sticking to the top of the page while scrolling.

Ref: http://www.nngroup.com/articles/mobile-accordions/

The demo page doesn't seem to have this behaviour and couldn't find any reference about something similar.

**Comment by donnielrt** [comment]
Hi @nuthinking, thanks for the suggestion! We don't currently have this in our roadmap, but will consider it during feature planning, thanks!
