### ISSUE TITLE
No jQuery/Zepto

### ISSUE THREAD

**Issue by toby1kenobi** [mobify/bellows#59]
In your example (http://mobify.github.io/bellows/) neither jQuery nor Zepto is included, is this a mistake? I'm having some weird problems trying to get a version to work, and trying to nail down exactly what's required.

Thanks.

**Comment by tedtate** [comment]
If you aren't using `require.js` (or similar) to bundle your files then you will need to include jQuery or Zepto in your HTML before Bellows.

From the usage section of the docs page:
```
<!-- Include dependencies -->
<script src="zepto.min.js"></script>
<script src="velocity.min.js"></script>

<!-- Include bellows.js -->
<script src="bellows.min.js"></script>
```

**Comment by toby1kenobi** [comment]
Ok, thanks for clarifying

**Comment by donnielrt** [comment]
Thanks @toby1kenobi, gonna close this issue unless you have follow-up questions :)
